import "~/styles/globals.css";

import { type Metadata } from "next";
import { Space_Grotesk, Inter } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import Providers from "./providers";
import NextTopLoader from 'nextjs-toploader';

export const metadata: Metadata = {
  title: "Canvas",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.svg" }],
};

const grotesk = Space_Grotesk({
  subsets: ['latin'],
  weight: ['400', '700'],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode}>) {
  return (
    <html  lang="en" className={`${inter.className} antialiased`} suppressHydrationWarning={true}>
      <body suppressHydrationWarning={true}>
        <TRPCReactProvider>
            <Providers>
               <NextTopLoader height={4} color="#38bdf8" showSpinner={false} easing="ease"/>
                 {children}
            </Providers>
          </TRPCReactProvider>
      </body>
    </html>
  );
}
